Computer Based Exam (CBE)/CBE/urls.py
from django.contrib import admin
from django.urls import path, include
from student.views import home, student_log

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  path('student/', include('student.urls', namespace='student')),
                  path('candidate/', student_log, name='student'),
                  path('adminstrator/', include('adminstrator.urls', namespace='adminstrator')),
                  path('doctor/', include('doctor.urls', namespace='doctor')),
                  path('exam/', include('exam.urls', namespace='exam')),
                  path('detection/', include('detection.urls', namespace='detection')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Computer Based Exam (CBE)/doctor/urls.py
from django.conf.urls import url
from . import views

app_name = 'doctor'

urlpatterns = [
    url('information_prof/(?P<d_ssn>\d+)/', views.information_prof, name='information_prof'),
    url('add_exam/(?P<c_id>\d+)/', views.add_exam, name='add_exam'),
    url('add_exam_form/', views.add_exam_form, name='add_exam_form'),
    url('Add_question/', views.Addquestion, name='Add_question'),
    url('add_exam_Q/', views.add_exam_Q, name='add_exam_Q'),
    url('test_bank_prof/', views.test_bank_prof, name='test_bank_prof'),
    url('add_test_bank/', views.add_test_bank, name='add_test_bank'),
    url('add_test_bank_Q/', views.add_test_bank_Q, name='test_bank_Q'),
    url('exam_courses/', views.exam_courses, name='exam_courses'),
    url('test_courses/', views.test_courses, name='test_courses'),
    url('make_test/(?P<c_id>\d+)/', views.add_test_bank_form, name='make_test'),

]

Computer Based Exam (CBE)/doctor/models.py
from django.db import models
from adminstrator.models import Administrator


class Doctor(models.Model):
    D_name = models.CharField(max_length=80)
    D_id = models.BigIntegerField(null=False, unique=True)
    D_ssn = models.BigIntegerField(primary_key=True, unique=True)
    # D_phone = models.BigIntegerField(null=False, default=None)
    D_address = models.CharField(max_length=80)
    D_faculty = models.CharField(max_length=50, default="")
    D_department = models.CharField(max_length=20, default="")
    A_ssn = models.ForeignKey(Administrator, default=None, null=False, on_delete=models.CASCADE)


class Test(models.Model):
    Te_id = models.IntegerField(primary_key=True, unique=True)
    Te_course = models.CharField(max_length=30)
    Te_Academic_year = models.CharField(null=False, max_length=10)
    Te_degree = models.IntegerField(null=False, default=None)
    Te_number_of_Q = models.IntegerField(null=False, default=None)
    D_ssn = models.ForeignKey(Doctor, default=None, on_delete=models.CASCADE)


class Course(models.Model):
    C_id = models.AutoField(primary_key=True)
    C_name = models.CharField(max_length=30)
    C_number = models.CharField(max_length=30, default=None)


class Test_question(models.Model):
    Qsi_id = models.AutoField(null=False, primary_key=True, unique=True)
    Question = models.CharField(null=False, max_length=500)
    Ans1 = models.CharField(null=False, max_length=300)
    Ans2 = models.CharField(null=False, max_length=300)
    Ans3 = models.CharField(null=False, max_length=300)
    Ans4 = models.CharField(null=False, max_length=300)
    Question_no = models.IntegerField(default=0)
    Right_ans = models.CharField(null=False, max_length=1, default=None)
    Te_id = models.ForeignKey(Test, default=None, on_delete=models.CASCADE)

Computer Based Exam (CBE)/doctor/views.py
from _elementtree import ParseError

from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.db.models import Count
from exam import models as ex
from .models import Doctor, Course, Test, Test_question


def information_prof(request, d_ssn=None):
    a = get_object_or_404(Doctor, D_ssn=d_ssn)
    request.session["doctor_ssn"] = d_ssn
    context = {'name': a.D_name,
               'd_ssn': a.D_ssn,
               'd_id': a.D_id,
               'd_faculty': a.D_faculty,
               'd_department': a.D_department,
               'd_address': a.D_address,
               }
    return render(request, 'doctor/Information_prof.html', context)


def add_exam_form(request):
    a = get_object_or_404(Doctor, D_ssn=request.session['doctor_ssn'])
    course = get_object_or_404(Course, C_id=request.session['course_id'])
    print()
    exam = ex.Exams(
        Ex_id=request.POST['ex_id'],
        Ex_course=course.C_name,
        Ex_Academic_year=request.POST['year'],
        Ex_Duration=request.POST['duration'],
        Ex_number_of_Q=request.POST['count'],
        Ex_degree=request.POST['degree'],
        D_ssn_id=request.session['doctor_ssn'])
    exam.save()
    request.session['exam_id'] = request.POST['ex_id']
    request.session['no_question'] = request.POST['count']

    # exam = get_object_or_404(ex.Exams, Ex_id=exam.Ex_id)
    context = {'name': a.D_name,
               'd_ssn': a.D_ssn,
               'ex_id': exam.Ex_id,
               'count': 1,
               'no_question': request.POST['count']}
    return render(request, 'doctor/add_exam_Q_input.html', context)


def add_exam(request, c_id):
    a = get_object_or_404(Doctor, D_ssn=request.session['doctor_ssn'])
    request.session['course_id'] = c_id

    # exam = ex.Exams.objects.filter(Ex_id=ex_id)
    course = Course.objects.filter()
    context = {'name': a.D_name,
               'd_ssn': a.D_ssn,
               'count': 1}
    return render(request, 'doctor/add_exam_prof.html', context)


def add_exam_Q(request):
    a = get_object_or_404(Doctor, D_ssn=request.session['doctor_ssn'])
    context = {'name': a.D_name,
               'd_ssn': a.D_ssn,
               'ex_id': 1,
               'count': 1,
               'no_question': request.session['no_question']}
    return render(request, 'doctor/add_exam_Q_input.html', context)


def Addquestion(request):
    a = get_object_or_404(Doctor, D_ssn=request.session['doctor_ssn'])
    b = get_object_or_404(ex.Exams, Ex_id=request.session['exam_id'])
    count = ex.ex_contain_qsi.objects.filter(Ex_id=request.session['exam_id']).count()
    c = count + 1
    question = ex.ex_contain_qsi(
        Question=request.POST['question'],
        Ans1=request.POST['answer1'],
        Ans2=request.POST['answer2'],
        Ans3=request.POST['answer3'],
        Ans4=request.POST['answer4'],
        Right_ans=request.POST['right'],
        Question_no=c,
        Ex_id_id=request.session['exam_id'])
    question.save()
    n_question = b.Ex_number_of_Q
    count = ex.ex_contain_qsi.objects.filter(Ex_id=request.session['exam_id']).count()
    context = {'name': a.D_name,
               'd_ssn': a.D_ssn,
               'ex_id': b.Ex_id,
               'count': c,
               'no_question': n_question}
    if count < n_question:
        return render(request, 'doctor/add_exam_Q_input.html', context)
    else:
        return redirect('doctor:exam_courses')


def test_bank_prof(request):
    a = get_object_or_404(Doctor, D_ssn=request.session['doctor_ssn'])
    course = Course.objects.filter(C_id=request.session['course_id'])

    context = {
        'd_ssn': a.D_ssn,
        'course': course.C_name,
        'course': course
    }

    return render(request, 'doctor/add_test_bank.html', context)


def add_test_bank(request):
    a = get_object_or_404(Doctor, D_ssn=request.session['doctor_ssn'])
    cours = get_object_or_404(Course, C_id=request.session['course_id'])
    test = Test(
        Te_id=request.POST['ex_id'],
        Te_course=cours.C_name,
        Te_Academic_year=request.POST['year'],
        Te_degree=request.POST['degree'],
        Te_number_of_Q=request.POST['count'],
        D_ssn_id=request.session['doctor_ssn'])
    test.save()
    context = {'name': a.D_name,
               'd_ssn': a.D_ssn,
               'count': 1,
               'no_question': request.POST['count'],
               'courses': cours,
               }
    request.session['test_id'] = request.POST['ex_id']

    return render(request, 'doctor/test_bank_Q_input.html', context)


def add_test_bank_form(request, c_id=None):
    request.session['course_id'] = c_id
    a = get_object_or_404(Doctor, D_ssn=request.session['doctor_ssn'])
    context = {
        'd_ssn': request.session['doctor_ssn'],
        'name': a.D_name,
    }
    return render(request, 'doctor/add_test_bank.html', context)


def add_test_bank_Q_form(request):
    a = get_object_or_404(Doctor, D_ssn=request.session['doctor_ssn'])
    context = {
        'd_ssn': request.session['doctor_ssn'],
        'name': a.D_name,
    }
    return render(request, 'doctor/test_bank_Q_input.html', context)


def add_test_bank_Q(request):
    a = get_object_or_404(Doctor, D_ssn=request.session['doctor_ssn'])
    b = get_object_or_404(Test, Te_id=request.session['test_id'])
    count = Test_question.objects.filter(Te_id=request.session['test_id']).count()
    course = Course.objects.filter();
    c = count + 1
    question = Test_question(
        Question=request.POST['question'],
        Ans1=request.POST['answer1'],
        Ans2=request.POST['answer2'],
        Ans3=request.POST['answer3'],
        Ans4=request.POST['answer4'],
        Right_ans=request.POST['right'],
        Question_no=c,
        Te_id_id=request.session['test_id'])
    question.save()
    n_question = b.Te_number_of_Q
    context = {'name': a.D_name,
               'd_ssn': a.D_ssn,
               'ex_id': b.Te_id,
               'count': c,
               'no_question': n_question,
               'course': course,
               }
    if count < n_question:
        return render(request, 'doctor/test_bank_Q_input.html', context)
    else:
        return render(request, 'doctor/test_courses.html', context)
        # redirect('doctor:test_courses')


def exam_courses(request):
    a = get_object_or_404(Doctor, D_ssn=request.session['doctor_ssn'])
    course = None
    if (Course.objects.filter()):
        course = Course.objects.filter()
    context = {'name': a.D_name,
               'd_ssn': a.D_ssn,
               'course': course}
    return render(request, 'doctor/exam_courses.html', context)


def test_courses(request):
    a = get_object_or_404(Doctor, D_ssn=request.session['doctor_ssn'])
    course = None
    if (Course.objects.filter()):
        course = Course.objects.filter()
    context = {'name': a.D_name,
               'd_ssn': a.D_ssn,
               'course': course}
    return render(request, 'doctor/test_courses.html', context)

Computer Based Exam (CBE)/templates/doctor/add_exam_Q_input.html
{% load static %}
<html>

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'resources/style/teplate.css' %}" rel="stylesheet">
    <script src="{% static 'resources/js/jquery-1.js' %}"></script>
    <script src="{% static 'resources/js/bootstrap.js' %}"></script>
    <title>Test Bank</title>
    <style type="text/css">
        a {
            cursor: pointer;
        }

        tab_text {
            text-transform: uppercase;
            font-weight: normal;
            font-family: Lucida Sans Unicode Lucida Grande sans-serif;
            text-shadow: 1px 1px 0 #ffffff;
            font-size: 1.071em
        }

        .label-attempt {
            background-color: #fff;
            padding: 1px 2px;
            color: #666;
            border: solid 1px;
            border-color: #666;
            text-shadow: 0 0px 0 rgba(0, 0, 0, 0);
            font-weight: normal;
        }

        #question {
            width: 800px;
            height: 80px;
            font-size: 20px;
            -webkit-appearance: textarea;
        }

        #answer {
            width: 700px;
            height: 40px;
            font-size: 20px;
        }

        #lnkFreeTakeTest {
            margin-left: 730px;
        }


    </style>

</head>

<body class="inner" cz-shortcut-listen="true" style="zoom: 1;">
<div class="main container">
    <div class="row">
        <div class="left-sidebar span3">
            <div id="logo">
                <img src="{% static 'resources/images/inner-mkcloeslogo.png' %}" alt="OES">
            </div>
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span
                                class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                        </a>
                        <div class="nav-collapse collapse">
                            <ul class="nav side-menu">
                                <li><a href="{% url 'doctor:information_prof' d_ssn %}"><i class="icon-th-large"></i>
                                    Information</a></li>
                                <li><a href="{% url 'doctor:test_courses' %}"><i class="icon-th-large"></i> Add Test
                                    Bank</a></li>
                                <li><a href="{% url 'doctor:exam_courses' %}"><i class="icon-th-large"></i> Add Exam</a>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content span9">
            <div class="content-above">
                <div class="holder">
                    <div class="profile">
                        <div class="holder">
                            <div class="display-pic">
                                <div class="dp">
                                    <img src="{% static 'resources/images/defaultCandidate.jpg' %}">
                                </div>
                            </div>
                            <div class="display-info">
                                <p>{{ name }} </p>
                                <div class="btn-group">
                                    <a href="{% url 'student' %}" class="btn btn-orange">
                                        <font>Logout</font>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-top">
                <div class="holder">
                </div>
            </div>
            <div class="main-content">
                <fieldset class="well">

                    <legend>
                            <span><img src="{% static 'resources/images/dashboard.png' %}" alt=""> Exam<span
                                    class="pull-right"></span>
                            </span></legend>


                    <div class="holder">
                        <div id="tabbable">
                            <ul class="nav nav-tabs" id="myTab">
                                <li class="active"><a href="#" data-toggle="tab" class="tab_text"
                                                      style=" font-weight: bold; font-size:18px; text-shadow: 2px 2px 0 #ffffff;">Add
                                    Question </a></li>

                            </ul>
                        </div>
                        <div id="showScheduledPapers">


                            <div class="box">
                                <div class="box-body">
                                    <form id="add_student" action="{% url 'doctor:Add_question' %}" method="POST">
                                        {% csrf_token %}
                                        <table class="table table-bordered table-complex" style="border-top: 0;">
                                            <thead>
                                            <tr>
                                                <th colspan="3" class="text-left"></th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>

                                                <td><p style="font-size:18px;"><i class="icon-user "></i><strong>&nbsp;&nbsp;Question:(
                                                    &nbsp;{{ count }}/{{ no_question }}&nbsp;)</strong></p>
                                                    <textarea type="text" class="form-control" id="question"
                                                              name="question" required></textarea>
                                                    <p style="font-size:18px;"><i class="icon-user "></i><strong>&nbsp;&nbsp;Answers:-&nbsp;&nbsp;</strong>
                                                    </p>
                                                    <label style="font-size:18px;" class="icon-user">A)</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                                    <input type="text" class="form-control" id="answer" name="answer1"
                                                           required><br>
                                                    <label style="font-size:18px;" class="icon-user">B)</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                                    <input type="text" class="form-control" id="answer" name="answer2"
                                                           required><br>
                                                    <label style="font-size:18px;" class="icon-user">C)</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                                    <input type="text" class="form-control" id="answer" name="answer3"
                                                           required><br>
                                                    <label style="font-size:18px;" class="icon-user">D)</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                                    <input type="text" class="form-control" id="answer" name="answer4"
                                                           required><br>
                                                    <label style="font-size:18px;" class="icon-user">&#10004;)</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                                    <input type="text" class="form-control" id="answer" name="right"
                                                           required pattern="[A B C D a b c d]+" title="string only"
                                                           maxlength="1"><br>
                                                    <br>
                                                    <button id="lnkFreeTakeTest" data-mode="FullScreen" type="submit"
                                                            data-dcidcnt="" class="btn btn-greener lnkFreeTakeTest">ADD
                                                    </button>


                                            </tr>

                                            </tbody>

                                        </table>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>

            </div>
            <br>

            <div class="footer span9">
                <div class="holder">
                    <p class="pull-left">Copyright © 2018 CBE. All Rights Reserved.</p>
                    <a id="to-top" class="btn btn-grey pull-right" href="#"><i class="icon-chevron-up icon-greyer"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>

</body>

</html>

Computer Based Exam (CBE)/templates/doctor/add_exam_prof.html
{% load static %}
<html>

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'resources/style/teplate.css' %}" rel="stylesheet">
    <script src="{% static 'resources/js/jquery-1.js' %}"></script>
    <script src="{% static 'resources/js/bootstrap.js' %}"></script>
    <title>DashBoard</title>
    <style type="text/css">
        a {
            cursor: pointer;
        }

        tab_text {
            text-transform: uppercase;
            font-weight: normal;
            font-family: Lucida Sans Unicode Lucida Grande sans-serif;
            text-shadow: 1px 1px 0 #ffffff;
            font-size: 1.071em
        }

        .label-attempt {
            background-color: #fff;
            padding: 1px 2px;
            color: #666;
            border: solid 1px;
            border-color: #666;
            text-shadow: 0 0px 0 rgba(0, 0, 0, 0);
            font-weight: normal;
        }

        #answer {
            width: 600px;
            height: 40px;
            font-size: 20px;
            margin-left: 20px;
        }

        #lnkFreeTakeTest {
            margin-left: 730px;
        }

    </style>

</head>

<body class="inner" cz-shortcut-listen="true" style="zoom: 1;">
<div class="main container">
    <div class="row">
        <div class="left-sidebar span3">
            <div id="logo">
                <img src="{% static 'resources/images/inner-mkcloeslogo.png' %}" alt="OES">
            </div>
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span
                                class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                        </a>
                        <div class="nav-collapse collapse">
                            <ul class="nav side-menu">
                                <li><a href="{% url 'doctor:information_prof' d_ssn %}"><i class="icon-th-large"></i>
                                    Information</a></li>
                                <li><a href="{% url 'doctor:test_courses' %}"><i class="icon-th-large"></i> Add Test
                                    Bank</a></li>
                                <li><a href="{% url 'doctor:exam_courses' %}"><i class="icon-th-large"></i> Add
                                    Exam</a></li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content span9">
            <div class="content-above">
                <div class="holder">
                    <div class="profile">
                        <div class="holder">
                            <div class="display-pic">
                                <div class="dp">
                                    <img src="{% static 'resources/images/defaultCandidate.jpg' %}">
                                </div>
                            </div>
                            <div class="display-info">
                                <p>{{ name }} </p>
                                <div class="btn-group">
                                    <a href="{% url 'student' %}" class="btn btn-orange">
                                        <font>Logout</font>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-top">
                <div class="holder">
                </div>
            </div>
            <div class="main-content">
                <fieldset class="well">

                    <legend>
                            <span><img src="{% static 'resources/images/dashboard.png' %}" alt=""> Add Exam<span
                                    class="pull-right"></span>
                            </span></legend>
                    <div class="holder">
                        <div id="tabbable">
                            <ul class="nav nav-tabs" id="myTab">
                                <li class="active"><a href="#" data-toggle="tab" class="tab_text"
                                                      style=" font-weight: bold; font-size:18px; text-shadow: 2px 2px 0 #ffffff;">Exam </a>
                                </li>

                            </ul>
                        </div>
                        <div id="showScheduledPapers">


                            <div class="box">
                                <div class="box-body">
                                    <form id="add_student" action="{% url 'doctor:add_exam_form' %}"
                                          method="POST">
                                        {% csrf_token %}
                                        <table class="table table-bordered table-complex" style="border-top: 0;">
                                            <thead>
                                            <tr>
                                                <th colspan="3" class="text-left"></th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>

                                                <td>
                                                    <label style="font-size:18px;" class="form_label">Exam ID:-</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                                    <input type="text" class="form-control" id="answer" name="ex_id"
                                                           required pattern="[0-9]+" title="number only"><br>
                                                    <label style="font-size:18px;" class="form_label">Academic
                                                        Year:-</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text"
                                                                                                      class="form-control"
                                                                                                      id="answer"
                                                                                                      name="year"
                                                                                                      required
                                                                                                      pattern="[0-9]+"
                                                                                                      title="number only"><br>
                                                    <label style="font-size:18px;" class="form_label">Duration:-</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                                    <input type="text" class="form-control" id="answer" name="duration"
                                                           required pattern="[0-9]+" title="number only"><br>
                                                    <label style="font-size:18px;" class="form_label">Number of
                                                        Questions:-</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text"
                                                                                                           class="form-control"
                                                                                                           id="answer"
                                                                                                           name="count"
                                                                                                           required
                                                                                                           pattern="[0-9]+"
                                                                                                           title="number only"><br>
                                                    <label style="font-size:18px;" class="form_label">Degree:-</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                                    <input type="text" class="form-control" id="answer" name="degree"
                                                           required pattern="[0-9]+" title="number only"><br>
                                                    <br>
                                                    <button id="lnkFreeTakeTest" data-mode="FullScreen" type="submit"
                                                            data-dcidcnt="" class="btn btn-greener lnkFreeTakeTest">ADD
                                                    </button>


                                            </tr>

                                            </tbody>
                                        </table>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>

            </div>
            <br>

            <div class="footer span9">
                <div class="holder">
                    <p class="pull-left">Copyright © 2018 CBE. All Rights Reserved.</p>
                    <a id="to-top" class="btn btn-grey pull-right" href="#"><i class="icon-chevron-up icon-greyer"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>

</body>

</html>