Computer Based Exam (CBE)/CBE/urls.py
from django.contrib import admin
from django.urls import path, include
from student.views import home, student_log

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  path('student/', include('student.urls', namespace='student')),
                  path('candidate/', student_log, name='student'),
                  path('adminstrator/', include('adminstrator.urls', namespace='adminstrator')),
                  path('doctor/', include('doctor.urls', namespace='doctor')),
                  path('exam/', include('exam.urls', namespace='exam')),
                  path('detection/', include('detection.urls', namespace='detection')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Computer Based Exam (CBE)/detection/urls.py
from django.conf.urls import url
from . import views

app_name = 'detetion'

urlpatterns = [
    url('', views.index, name='index'),

]

Computer Based Exam (CBE)/exam/urls.py
from django.conf.urls import url
from . import views

app_name = 'exam'

urlpatterns = [
    url('instruction/(?P<ex_id>\d+)/', views.instruction, name='instruction'),
    url('test/', views.test, name='test'),
    url('blank/(?P<qn>\d+)/', views.blank, name='blank'),
    url('question/', views.get_question_byno, name='question'),
    url('Result/', views.result, name='result'),
    url('Answer/', views.answer, name='answer'),

]

Computer Based Exam (CBE)/student/urls.py
from django.conf.urls import url
from . import views

app_name = 'student'

urlpatterns = [
    url('login/', views.student_log, name='login'),
    url('dashboard/', views.dashboard, name='dashboard'),
    url('information/', views.Information, name='information'),
    url('test-bank/', views.test_bank, name='test-bank'),
    url('requirement/(?P<stu_ssn>\d+)/', views.requirement, name='requirement'),
    url('instruction-test/(?P<stu_ssn>\d+)/', views.instruction_test, name='instruction-test'),
    url('blank-bank/', views.blank_bank, name='blank-bank'),
    url('log/', views.log, name='log'),
    url('result/(?P<ex_id>\d+)', views.result, name='result'),

]

Computer Based Exam (CBE)/student/models.py
from django.db import models


from adminstrator.models import Administrator


class Student(models.Model):
    Stu_name = models.CharField(null=False, max_length=50)
    Stu_id = models.BigIntegerField(null=False, unique=True)
    Stu_ssn = models.BigIntegerField(primary_key=True, null=False, unique=True)
    Stu_faculty = models.CharField(null=False, max_length=50)
    Stu_department = models.CharField(null=False, max_length=50)
    Stu_level = models.BigIntegerField(null=False)
    Stu_address = models.CharField(max_length=80)
    A_ssn = models.ForeignKey(Administrator,default=None,on_delete=models.CASCADE)

Computer Based Exam (CBE)/student/forms.py
from django.core import validators
from django.forms import CharField

from django import forms


#class Register(forms.Form):
    #stu_id= forms.BigIntegerField (label='', max_length=80, required=True)
    #stu_ssn = forms.BigIntegerField (label='', max_length=64, required=True)
    #surname = forms.CharField(label='sur name', max_length=64,  required=True)
    #email = forms.EmailField()

Computer Based Exam (CBE)/student/views.py
from django.urls import reverse

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from .models import Student
from doctor.models import Doctor
from django.contrib import messages
from exam import models as ex


def home(request):
    return render(request, 'student/index.html', {})


def student_log(request):
    return render(request, 'student/student_log.html', {})


def log(request):
    if request.method == 'POST':

        u = request.POST['id']
        p = request.POST['password']
        if u != "" and p != "":
            if Student.objects.filter(Stu_id=u, Stu_ssn=p):
                request.session['student_ssn'] = p
                return redirect('student:dashboard')
            elif Doctor.objects.filter(D_id=u, D_ssn=p):
                request.session['doctor_ssn'] = p
                a = Doctor.objects.get(D_id=u, D_ssn=p)

                return redirect('doctor:information_prof', d_ssn=a.D_ssn)
            else:
                messages.error(request, 'ID or password not correct')
                return render(request, 'student/student_log.html', {})
        else:
            messages.error(request, 'ID or password not correct')
            return render(request, 'student/student_log.html', {})


def dashboard(request):
    a = get_object_or_404(Student, Stu_ssn=request.session['student_ssn'])
    exam = ex.Exams.objects.filter(Ex_Academic_year=a.Stu_level)
    l_exam = ex.stu_do_ex.objects.filter(Stu_ssn_id=request.session['student_ssn'])
    #if request.session['exam_id'] is not None:
    # del request.session['exam_id']
    #if request.session['Question_n'] is not None:
    # del request.session['exam_id']

    # query = '''SELECT * FROM exam_exams where Ex_Academic_year=%s  Ex_ssn not in
    # (select * from exam_stu_do_ex where exam_stu_do_ex.Ex_id_id = exam_exams.Ex_id
    # and exam_stu_do_ex.Stu_ssn_id = %s  ) '''[int(a.Stu_level): int(a.Stu_ssn)]
    # new_exam = ex.Exams.objects.raw(query)

    context = {'name': a.Stu_name,
               'stu_exam': exam,
               'l_exam': l_exam}
    return render(request, 'student/dashboard.html', context)


def Information(request):
    a = get_object_or_404(Student, Stu_ssn=request.session['student_ssn'])
    context = {'name': a.Stu_name,
               'stu_ssn': a.Stu_ssn,
               'stu_id': a.Stu_id,
               'stu_faculty': a.Stu_faculty,
               'stu_department': a.Stu_department,
               'stu_level': a.Stu_level,
               'stu_address': a.Stu_address,
               }

    return render(request, 'student/Information.html', context)


def result(request, ex_id):
    exam = get_object_or_404(ex.Exams, Ex_id=ex_id)
    reslt = get_object_or_404(ex.stu_do_ex, Stu_ssn_id=request.session['student_ssn'],
                              Ex_id_id=ex_id)
    context = {
        'course__n': reslt.Ex_course,
        'count': exam.Ex_number_of_Q,
        'answered': " ",
        'total_degree': reslt.Total_degree,
        'degree': reslt.Stu_degree,
        'passed': reslt.State,
        'stu_name': reslt.Stu_name,
        'stu_ssn': reslt.Stu_ssn_id,
    }
    return render(request, 'exam/result.html', context)


def test_bank(request):
    a = get_object_or_404(Student, Stu_ssn=request.session['student_ssn'])
    context = {'name': a.Stu_name,
               'stu_ssn': a.Stu_ssn}
    return render(request, 'student/test_bank.html', context)


def back(request):
    return render(request, 'student/index.html')


def instruction_test(request, stu_ssn=None):
    a = get_object_or_404(Student, Stu_ssn=stu_ssn)
    context = {'name': a.Stu_name,
               'stu_ssn': a.Stu_ssn}
    return render(request, 'student/instruction_test_bank.html', context)


def requirement(request, stu_ssn=None):
    a = get_object_or_404(Student, Stu_ssn=stu_ssn)
    context = {'name': a.Stu_name,
               'stu_ssn': a.Stu_ssn}
    return render(request, 'student/test_test_bank.html', context)


def blank_bank(request):
    a = get_object_or_404(Student, Stu_ssn=request.session['student_ssn'])
    context = {'name': a.Stu_name,
               'stu_ssn': a.Stu_ssn}
    return render(request, 'student/blank_bank.html', context)

Computer Based Exam (CBE)/templates/student/blank_bank.html
{% load static %}
<html>
<head>
</head>
<body>
<h1>test_bank</h1>
</body>
</html>

Computer Based Exam (CBE)/templates/student/dashboard.html
{% load static %}
<html>

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'resources/style/teplate.css' %}" rel="stylesheet">
    <script src="{% static 'resources/js/jquery-1.js' %}"></script>
    <script src="{% static 'resources/js/bootstrap.js' %}"></script>
    <title>DashBoard</title>
    <style type="text/css">
        {
            cursor: pointer
        ;
        }

        tab_text {
            text-transform: uppercase;
            font-weight: normal;
            font-family: Lucida Sans Unicode Lucida Grande sans-serif;
            text-shadow: 1px 1px 0 #ffffff;
            font-size: 1.071em
        }

        .label-attempt {
            background-color: #fff;
            padding: 1px 2px;
            color: #666;
            border: solid 1px;
            border-color: #666;
            text-shadow: 0 0px 0 rgba(0, 0, 0, 0);
            font-weight: normal;
        }

    </style>

</head>

<body class="inner" cz-shortcut-listen="true" style="zoom: 1;">
<div class="main container">
    <div class="row">
        <div class="left-sidebar span3">
            <div id="logo">
                <img src="{% static 'resources/images/inner-mkcloeslogo.png' %}" alt="OES">
            </div>
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span
                                class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                        </a>
                        <div class="nav-collapse collapse">
                            <ul class="nav side-menu">
                                <li><a href="{% url 'student:dashboard' %}"><i class="icon-th-large"></i>
                                    Dashboard</a></li>
                                <li><a href="{% url 'student:information' %}"><i class="icon-th-large"></i>
                                    Information</a></li>
                                {#                                <li><a href="{% url 'student:test-bank' %}"><i class="icon-th-large"></i> Test#}
                                {#                                    Bank</a></li>#}
                                <li><a href="{% url 'detection:index' %}"><i class="icon-th-large"></i>
                                    Information</a></li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content span9">
            <div class="content-above">
                <div class="holder">
                    <div class="profile">
                        <div class="holder">
                            <div class="display-pic">
                                <div class="dp">
                                    <img src="{% static 'resources/images/defaultCandidate.jpg' %}">
                                </div>
                            </div>
                            <div class="display-info">
                                <p>{{ name }}</p>
                                <div class="btn-group">
                                    <a href="{% url 'student' %}" class="btn btn-orange">
                                        <font>Logout</font>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-top">
                <div class="holder">
                </div>
            </div>
            <div class="main-content">
                <fieldset class="well">

                    <legend>
                            <span><img src="{% static 'resources/images/dashboard.png' %}" alt=""> Dashboard<span
                                    class="pull-right"></span>
                            </span></legend>


                    <div class="holder">
                        <div id="tabbable">
                            <ul class="nav nav-tabs" id="myTab">
                                <li class="active"><a href="#" data-toggle="tab" class="tab_text"
                                                      style=" font-weight: bold; font-size:18px; text-shadow: 2px 2px 0 #ffffff;">Active
                                    Test </a></li>

                            </ul>
                        </div>
                        <div id="showScheduledPapers">


                            <div class="box">
                                <div class="box-body">
                                    <table class="table table-bordered table-complex" style="border-top: 0;">
                                        <thead>
                                        <tr>
                                            <th colspan="3" class="text-left"></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for e in stu_exam %}

                                            <tr>
                                                <td>
                                                    <p style="font-size:18px;"><i class="icon-user "></i><strong>&nbsp;&nbsp; {{ e.Ex_course }}&nbsp;&nbsp;</strong><span
                                                            class="label label-success">New</span></p>

                                                </td>

                                                <td class="text-center">
                                                    <a id="lnkFreeTakeTest" data-mode="FullScreen" data-dcidcnt=""
                                                       class="btn btn-greener lnkFreeTakeTest"
                                                       data-lnk="instruction.html"
                                                       href="{% url 'exam:instruction' e.Ex_id %}">Take A Test</a>

                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                        <div id="tabbable">
                            <ul class="nav nav-tabs" id="myTab">
                                <li class="active"><a href="#" data-toggle="tab" class="tab_text"
                                                      style=" font-weight: bold; font-size:18px; text-shadow: 2px 2px 0 #ffffff;">Last
                                    Test </a></li>
                            </ul>
                        </div>

                        <div id="showScheduledPapers">


                            <div class="box">
                                <div class="box-body">
                                    <table class="table table-bordered table-complex" style="border-top: 0;">
                                        <thead>
                                        <tr>
                                            <th colspan="3" class="text-left"></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for e in l_exam %}

                                            <tr>
                                                <td>
                                                    <p style="font-size:18px;"><i class="icon-user "></i><strong>&nbsp;&nbsp; {{ e.Ex_course }}&nbsp;&nbsp;</strong>
                                                    </p>

                                                </td>

                                                <td class="text-center">
                                                    <a id="lnkFreeTakeTest" data-mode="FullScreen" data-dcidcnt=""
                                                       class="btn btn-greener lnkFreeTakeTest"
                                                       href="{% url 'student:result' e.Ex_id_id %}">result</a>

                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>

            </div>
            <br>

            <div class="footer span9">
                <div class="holder">
                    <p class="pull-left">Copyright © 2018 CBE. All Rights Reserved.</p>
                    <a id="to-top" class="btn btn-grey pull-right" href="#"><i class="icon-chevron-up icon-greyer"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>

</body>

</html>

Computer Based Exam (CBE)/templates/student/student_log.html
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/resources/style/template.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '/resources/style/selectFix.css' %}" type="text/css">
    <script src="{% static '/resources/js/jquery-1.9.0.min.js' %}"></script>
    <script src="{% static '/resources/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/resources/js/equalize.min.js' %}"></script>
    <script src="{% static '/resources/js/selectFix.js' %}"></script>
    <title>Candidate Login</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script>

       function date_time(id)
{
        date = new Date;
        year = date.getFullYear();
        month = date.getMonth();
        months = new Array('January', 'February', 'March', 'April', 'May', 'June', 'Jully', 'August', 'September', 'October', 'November', 'December');
        d = date.getDate();
        day = date.getDay();
        days = new Array('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday');
        h = date.getHours();
        if(h<10)
        {
                h = "0"+h;
        }
        m = date.getMinutes();
        if(m<10)
        {
                m = "0"+m;
        }
        s = date.getSeconds();
        if(s<10)
        {
                s = "0"+s;
        }
        result = ''+days[day]+' '+months[month]+' '+d+' '+year+' '+h+':'+m+':'+s;
        document.getElementById(id).innerHTML = "Server Time: "+result;
        setTimeout('date_time("'+id+'");','1000');
        return true;
}
    </script>
</head>

<body class="osp inner loginpage division-group" cz-shortcut-listen="true" style="zoom: 1;">
<div class="main">
    <div class="osp-header">
        <div class="container">
            <div class="row"></div>
        </div>
    </div>
    <div class="osp-content">
        <div class="container">
            <div class="row">
                <div class="span12 main-content">
                    <div class="content-holder">
                        <div class="well">
                            <div class="logo-holder text-center" style="padding-bottom : 10px;">
                                <img src="{% static 'resources/images/1_mkcloeslogo.png' %}" alt="OES School Project">
                                <hr id="dtSeprator"
                                    style="border-top: 1px solid rgb(153, 153, 153); margin-bottom: 10px;">
                                <div style="text-align: center;">
                                    <b><span id="Date" style="color: red"> <script type="text/javascript">window.onload = date_time('Date');</script></span></b>
                                </div>
                            </div>
                            <form id="loginform" action="{% url 'student:log' %}" method="POST">

                                {% csrf_token %}
                                <div class="login-type">
                                    <span class="btn btn-login-type-small"><i class="icon-osp-large icon-us"></i></span>Candidate
                                    Login
                                </div>
                                {% for message in messages %}

                                    <div class="alert alert-success" style="color:red">
                                        <a class="close" href="#" data-dismiss="alert">×</a>

                                        {{ message }}
                                    </div>
                                {% endfor %}
                                <div class="controls">
                                    <i class="icon-greyer icon-user"></i>

                                    <input id="userid" name="id" type="text" placeholder="ID" value="" required
                                           pattern="[0-9]+" title="number only">
                                </div>
                                <div class="controls">
                                    <i class="icon-greyer icon-lock"></i>
                                    <input id="pass" name="password" type="password" placeholder="Password" value=""
                                           required pattern="[0-9]+" title="number only">
                                </div>

                                <div class="text-center">
                                    <button class="btn btn-primary" type="submit" id="btnSave">Login</button>
                                </div>
                            </form>
                            <p class="version" style="text-align: center;">
                                <b>
                                    <a class="pull-left" href="../">Back</a>
                                    <span>Version : 1.0</span>
                                    <a class="pull-right" href="{% url 'adminstrator:log' %}">Administrator
                                        Login</a></b>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="osp-footer">
        <div class="container">
            <div class="row">
                <div class="span8 copyright">
                    <div class="holder">
                        Copyright ©
                        2018 CBE. All Rights Reserved.

                    </div>
                </div>
                <div class="span4 scroll-to-top">
                    <div class="holder">
                        <a id="to-top" class="btn" href="#"><i class="icon-osp-small icon-upper"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

</html>

Computer Based Exam (CBE)/templates/student/test_bank.html
{% load static %}
<html>

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'resources/style/teplate.css' %}" rel="stylesheet">
    <script src="{% static 'resources/js/jquery-1.js' %}"></script>
    <script src="{% static 'resources/js/bootstrap.js' %}"></script>
    <title>Test Bank</title>
    <style type="text/css">
        a {
            cursor: pointer;
        }

        tab_text {
            text-transform: uppercase;
            font-weight: normal;
            font-family: Lucida Sans Unicode Lucida Grande sans-serif;
            text-shadow: 1px 1px 0 #ffffff;
            font-size: 1.071em
        }

        .label-attempt {
            background-color: #fff;
            padding: 1px 2px;
            color: #666;
            border: solid 1px;
            border-color: #666;
            text-shadow: 0 0px 0 rgba(0, 0, 0, 0);
            font-weight: normal;
        }

    </style>

</head>

<body class="inner" cz-shortcut-listen="true" style="zoom: 1;">
<div class="main container">
    <div class="row">
        <div class="left-sidebar span3">
            <div id="logo">
                <img src="{% static 'resources/images/inner-mkcloeslogo.png' %}" alt="OES">
            </div>
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span
                                class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                        </a>
                        <div class="nav-collapse collapse">
                            <ul class="nav side-menu">
                                <li><a href="{% url 'student:dashboard' %}"><i class="icon-th-large"></i> Dashboard</a>
                                </li>
                                <li><a href="{% url 'student:information' %}"><i class="icon-th-large"></i> Information</a>
                                </li>
                                <li><a href="{% url 'student:test-bank' %}"><i class="icon-th-large"></i> Test Bank</a>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content span9">
            <div class="content-above">
                <div class="holder">
                    <div class="profile">
                        <div class="holder">
                            <div class="display-pic">
                                <div class="dp">
                                    <img src="{% static 'resources/images/defaultCandidate.jpg' %}">
                                </div>
                            </div>
                            <div class="display-info">
                                <p>{{ name }}</p>
                                <div class="btn-group">
                                    <a href="{% url 'student' %}" class="btn btn-orange">
                                        <font>Logout</font>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-top">
                <div class="holder">
                </div>
            </div>
            <div class="main-content">
                <fieldset class="well">

                    <legend>
                            <span><img src="{% static 'resources/images/dashboard.png' %}" alt=""> Test Bank<span
                                    class="pull-right"></span>
                            </span></legend>


                    <div class="holder">
                        <div id="tabbable">
                            <ul class="nav nav-tabs" id="myTab">
                                <li class="active"><a href="#" data-toggle="tab" class="tab_text"
                                                      style=" font-weight: bold; font-size:18px; text-shadow: 2px 2px 0 #ffffff;">Courses </a>
                                </li>

                            </ul>
                        </div>
                        <div id="showScheduledPapers">


                            <div class="box">
                                <div class="box-body">
                                    <table class="table table-bordered table-complex" style="border-top: 0;">
                                        <thead>
                                        <tr>
                                            <th colspan="3" class="text-left"></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td>
                                                <p style="font-size:18px;"><i class="icon-user "></i><strong>&nbsp;&nbsp;course
                                                    name&nbsp;&nbsp;</strong></p>

                                            </td>

                                            <td class="text-center">
                                                <a href="{% url 'student:instruction-test' stu_ssn %}"
                                                   id="lnkFreeTakeTest" data-mode="FullScreen" data-dcidcnt=""
                                                   class="btn btn-greener lnkFreeTakeTest">CH1</a>
                                                <a href="{% url 'student:instruction-test' stu_ssn %}"
                                                   id="lnkFreeTakeTest" data-mode="FullScreen" data-dcidcnt=""
                                                   class="btn btn-greener lnkFreeTakeTest">CH2</a>
                                                <a href="{% url 'student:instruction-test' stu_ssn %}"
                                                   id="lnkFreeTakeTest" data-mode="FullScreen" data-dcidcnt=""
                                                   class="btn btn-greener lnkFreeTakeTest">CH3</a>
                                                <a href="{% url 'student:instruction-test' stu_ssn %}"
                                                   id="lnkFreeTakeTest" data-mode="FullScreen" data-dcidcnt=""
                                                   class="btn btn-greener lnkFreeTakeTest">CH4</a>
                                                <a href="{% url 'student:instruction-test' stu_ssn %}"
                                                   id="lnkFreeTakeTest" data-mode="FullScreen" data-dcidcnt=""
                                                   class="btn btn-greener lnkFreeTakeTest">CH5</a>

                                            </td>
                                        </tr>

                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>

            </div>
            <br>

            <div class="footer span9">
                <div class="holder">
                    <p class="pull-left">Copyright © 2018 CBE. All Rights Reserved.</p>
                    <a id="to-top" class="btn btn-grey pull-right" href="#"><i class="icon-chevron-up icon-greyer"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>

</body>

</html>