Computer Based Exam (CBE)/CBE/urls.py
from django.contrib import admin
from django.urls import path, include
from student.views import home, student_log

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  path('student/', include('student.urls', namespace='student')),
                  path('candidate/', student_log, name='student'),
                  path('adminstrator/', include('adminstrator.urls', namespace='adminstrator')),
                  path('doctor/', include('doctor.urls', namespace='doctor')),
                  path('exam/', include('exam.urls', namespace='exam')),
                  path('detection/', include('detection.urls', namespace='detection')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Computer Based Exam (CBE)/exam/urls.py
from django.conf.urls import url
from . import views

app_name = 'exam'

urlpatterns = [
    url('instruction/(?P<ex_id>\d+)/', views.instruction, name='instruction'),
    url('test/', views.test, name='test'),
    url('blank/(?P<qn>\d+)/', views.blank, name='blank'),
    url('question/', views.get_question_byno, name='question'),
    url('Result/', views.result, name='result'),
    url('Answer/', views.answer, name='answer'),

]

Computer Based Exam (CBE)/student/urls.py
from django.conf.urls import url
from . import views

app_name = 'student'

urlpatterns = [
    url('login/', views.student_log, name='login'),
    url('dashboard/', views.dashboard, name='dashboard'),
    url('information/', views.Information, name='information'),
    url('test-bank/', views.test_bank, name='test-bank'),
    url('requirement/(?P<stu_ssn>\d+)/', views.requirement, name='requirement'),
    url('instruction-test/(?P<stu_ssn>\d+)/', views.instruction_test, name='instruction-test'),
    url('blank-bank/', views.blank_bank, name='blank-bank'),
    url('log/', views.log, name='log'),
    url('result/(?P<ex_id>\d+)', views.result, name='result'),

]

Computer Based Exam (CBE)/exam/models.py
from django.db import models
from django.db.models import CASCADE

from doctor.models import Doctor
from adminstrator.models import Administrator
from student.models import Student


class Exams(models.Model):
    Ex_id = models.IntegerField(primary_key=True, unique=True)
    Ex_course = models.CharField(max_length=30)
    Ex_Academic_year = models.CharField(null=False, max_length=10)
    Ex_Duration = models.IntegerField(null=False)
    Ex_degree = models.IntegerField(null=False)
    Ex_number_of_Q = models.IntegerField(null=False, default=None)
    D_ssn = models.ForeignKey(Doctor, default=None, on_delete=models.CASCADE)
    models.ManyToManyField(Student, through='stu_do_ex')
    Ex_date = models.DateField(null=True)
    models.ManyToManyField(Student, through='temp_ans')


class ex_contain_qsi(models.Model):
    Qsi_id = models.AutoField(null=False, primary_key=True, unique=True)
    Question = models.CharField(null=False, max_length=500)
    Ans1 = models.CharField(null=False, max_length=300)
    Ans2 = models.CharField(null=False, max_length=300)
    Ans3 = models.CharField(null=False, max_length=300)
    Ans4 = models.CharField(null=False, max_length=300)
    Question_no = models.IntegerField(default=0)
    Right_ans = models.CharField(null=False, max_length=1, default=None)
    Ex_id = models.ForeignKey(Exams, default=None, on_delete=models.CASCADE)


class supervisor(models.Model):
    Sup_id = models.IntegerField(null=False, unique=True)
    Sup_ssn = models.IntegerField(primary_key=True, unique=True)
    Sup_name = models.CharField(null=False, unique=True, max_length=50)
    Entry_code = models.IntegerField(null=False, unique=True)
    Phone = models.IntegerField()
    Address = models.CharField(max_length=80)
    A_ssn = models.ForeignKey(Administrator, default=None, on_delete=models.CASCADE)
    models.ManyToManyField(Exams)


class stu_do_ex(models.Model):
    Stu_ssn = models.ForeignKey(Student, on_delete=models.CASCADE)
    Ex_id = models.ForeignKey(Exams, on_delete=models.CASCADE)
    Stu_name = models.CharField(max_length=50)
    Ex_course = models.CharField(max_length=40)
    Total_degree = models.IntegerField()
    Stu_degree = models.IntegerField()
    State = models.CharField(max_length=20)


class temp_ans(models.Model):
    Stu_ssn = models.ForeignKey(Student, on_delete=models.CASCADE)
    Ex_id = models.ForeignKey(Exams, on_delete=models.CASCADE)
    Question_no = models.IntegerField()
    Answer = models.CharField(max_length=10, default=None)

Computer Based Exam (CBE)/exam/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, get_list_or_404

from .models import *


def instruction(request, ex_id):
    a = get_object_or_404(Student, Stu_ssn=request.session['student_ssn'])
    b = get_object_or_404(Exams, Ex_id=ex_id)
    # if (request.session['Question_n'] is True):
    #     del request.session.pop['Question_n']
    request.session['exam_id'] = ex_id
    request.session['Question_n'] = 1
    context = {'name': a.Stu_name,
               'stu_ssn': a.Stu_ssn,
               'ex_id': b.Ex_id}
    return render(request, 'exam/instruction.html', context)


def test(request):
    questions = get_list_or_404(ex_contain_qsi, Ex_id_id=request.session['exam_id'])
    exam = get_object_or_404(Exams, Ex_id=request.session['exam_id'])
    count = ex_contain_qsi.objects.filter(Ex_id_id=request.session['exam_id']).count()

    context = {
        'stu_ssn': request.session['student_ssn'],
        'ex_name': exam.Ex_course,
        'time': exam.Ex_Duration,
        'exam': questions,
        'count': count}
    return render(request, 'exam/test.html', context)


def blank(request, qn=None):
    print(" sameh" + qn)
    query = get_object_or_404(ex_contain_qsi, Ex_id_id=request.session['exam_id'], Question_no=qn)
    request.session['Question_n'] = qn
    if query is None:
        raise Http404
    ans = request.POST.get("ans", None)
    if ans in ["A", "B", "C", "D"]:
        t_ans = temp_ans(Stu_ssn_id=request.session['student_ssn'],
                         Ex_id_id=request.session['exam_id'],
                         Question_no=request.session['Question_n'],
                         Answer=ans)
        t_ans.save()
    context = {'exam': query}
    return render(request, 'exam/blank.html', context)


def get_question_byno(request):
    count = ex_contain_qsi.objects.filter(Ex_id_id=request.session['exam_id']).count()
    x = int(request.session['Question_n'])

    if (x < count):
        b = get_object_or_404(ex_contain_qsi, Ex_id_id=request.session['exam_id'], Question_no=x)
        request.session['Question_n'] = x +1
        context = {'ex_id': request.session['exam_id'],

                   'exam': b}
        return render(request, 'exam/blank.html', context)

    b = get_object_or_404(ex_contain_qsi, Ex_id_id=request.session['exam_id'], Question_no=x)
    request.session['Question_n'] = x + 1
    context = {
        'ex_id': request.session['exam_id'],
        'ans': '',
        'exam': b}
    return render(request, 'exam/blank.html', context)


def result(request):
    a = get_object_or_404(Student, Stu_ssn=request.session['student_ssn'])
    exam = get_object_or_404(Exams, Ex_id=request.session['exam_id'])
    right_ans = ex_contain_qsi.objects.filter(Ex_id_id=request.session['exam_id'])
    count = ex_contain_qsi.objects.filter(Ex_id=request.session['exam_id']).count()

    answered_q = temp_ans.objects.filter(Stu_ssn_id=request.session['student_ssn'],
                                         Ex_id_id=request.session['exam_id']).order_by('Question_no')

    performed_exam = stu_do_ex.objects.filter(Stu_ssn_id=request.session['student_ssn'],
                                              Ex_id_id=request.session['exam_id'])
    no_right_q = 0
    passed = "failed"

    answered = len(answered_q)
    degree = 0

    if (not performed_exam):
        for i in right_ans:
            x = i.Question_no
            ans = temp_ans.objects.filter(Stu_ssn_id=request.session['student_ssn'],
                                          Ex_id=request.session['exam_id'], Question_no=x).first()
            if ans != None and i.Right_ans == ans.Answer:
                no_right_q = no_right_q + 1
        degree = (no_right_q / int(count)) * int(exam.Ex_degree)

        if degree / int(exam.Ex_degree) >= 0.6:
            passed = "success"

        do_exam = stu_do_ex(Stu_ssn_id=request.session['student_ssn'],
                            Ex_id_id=request.session['exam_id'],
                            Stu_name=a.Stu_name,
                            Ex_course=exam.Ex_course,
                            Total_degree=exam.Ex_degree,
                            Stu_degree=degree,
                            State=passed)
        do_exam.save()
    # resl = stu_do_ex.objects.get(Stu_ssn_id=request.session['student_ssn'],
    #                              Ex_id_id=request.session['exam_id'])

    context = {'course__n': exam.Ex_course,
               'count': count,
               'answered': answered,
               'total_degree': exam.Ex_degree,
               'degree': degree,
               'passed': passed,
               'stu_name': a.Stu_name,
               'stu_ssn': a.Stu_ssn}

    return render(request, 'exam/result.html', context)


def answer(request):
    x = 0
    if int(request.session['Question_n']) < 1:
        x = 1
    else:
        x = int(request.session['Question_n'])-1
    ans = request.POST.get("ans", None)
    if ans in ['a', 'b', 'c', 'd']:
        q = get_object_or_404(ex_contain_qsi, Ex_id=request.session['exam_id'], Question_no=x)
        if (not q):
            t_ans = temp_ans(Stu_ssn_id=request.session['student_ssn'],
                             Ex_id_id=request.session['exam_id'],
                             Question_no=x,
                             Answer=ans)
            t_ans.save()

    b = get_object_or_404(ex_contain_qsi, Ex_id=request.session['exam_id'], Question_no=x)
    context = {
        'ex_id': request.session['exam_id'],
        'ans': ans,
        'exam': b
    }
    return render(request, 'exam/blank.html', context)

Computer Based Exam (CBE)/templates/exam/blank.html
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <style>
        h2 {
            color: red;
        }

        .ans {
            margin: 30px;
        }


        button {
            padding-top: 2px;
            h3: padding-bottom 3px;
            font-size: 12px;
            font-family: "Lucida Sans Unicode", "Lucida Grande", sans-serif;
            border: 1px solid #007251;
            color: #ffffff;
            background-color: #00af7c;
            display: inline-block;
            padding: 4px 12px;
            margin-bottom: 0;
            font-size: 14px;
            line-height: 20px;
            text-align: center;
            cursor: pointer;
            border-radius: 2px;
            box-shadow: inset 0 1px 0 rgba(255, 255, 255, .2), 0 1px 2px rgba(0, 0, 0, .05);
        }

        .n {
            position: absolute;
            bottom: 20px;
            right: 20px;
        }

        a {
            padding-top: 2px;
            h3: padding-bottom 3px;
            font-size: 12px;
            font-family: "Lucida Sans Unicode", "Lucida Grande", sans-serif;
            border: 1px solid #007251;
            color: #ffffff;
            background-color: #00af7c;
            display: inline-block;
            padding: 4px 12px;
            margin-bottom: 0;
            font-size: 14px;
            line-height: 20px;
            text-align: center;
            cursor: pointer;
            border-radius: 2px;
            box-shadow: inset 0 1px 0 rgba(255, 255, 255, .2), 0 1px 2px rgba(0, 0, 0, .05);
        }

    </style>
    <script>

    </script>
</head>
<body oncontextmenu="return false">
<form method="post" action="{% url 'exam:answer' %}">
    {% csrf_token %}
    <h2>({{ exam.Question_no }})&nbsp;{{ exam.Question }} </h2>
    <div class="ans">
        {% if ans == 'a' %}
            <h3><label><input type="radio" checked name="ans" value="a">{{ exam.Ans1 }}</label></h3>
            <h3><label><input type="radio" name="ans" value="b">{{ exam.Ans2 }}</label></h3>
            <h3><label><input type="radio" name="ans" value="c">{{ exam.Ans3 }}</label></h3>
            <h3><label><input type="radio" name="ans" value="d">{{ exam.Ans4 }}</label></h3>
        {% elif ans == 'b' %}

            <h3><label><input type="radio" name="ans" value="a">{{ exam.Ans1 }}</label></h3>
            <h3><label><input type="radio" checked name="ans" value="b">{{ exam.Ans2 }}</label></h3>
            <h3><label><input type="radio" name="ans" value="c">{{ exam.Ans3 }}</label></h3>
            <h3><label><input type="radio" name="ans" value="d">{{ exam.Ans4 }}</label></h3>
        {% elif ans == 'c' %}

            <h3><label><input id="ans1" type="radio" name="ans" value="a">{{ exam.Ans1 }}</label></h3>
            <h3><label><input id="ans1" type="radio" name="ans" value="b">{{ exam.Ans2 }}</label></h3>
            <h3><label><input id="ans1" type="radio" checked name="ans" value="c">{{ exam.Ans3 }}</label></h3>
            <h3><label><input type="radio" name="ans" value="d">{{ exam.Ans4 }}</label></h3>
        {% elif ans  == 'd' %}

            <h3><label><input id="ans1" type="radio" checked name="ans" value="a">{{ exam.Ans1 }}</label></h3>
            <h3><label><input id="ans1" type="radio" name="ans" value="b">{{ exam.Ans2 }}</label></h3>
            <h3><label><input id="ans1" type="radio" name="ans" value="c">{{ exam.Ans3 }}</label></h3>
            <h3><label><input type="radio" name="ans" value="d">{{ exam.Ans4 }}</label></h3>
        {% else %}

            <h3><label><input id="ans1" type="radio" name="ans" value="a">{{ exam.Ans1 }}</label></h3>
            <h3><label><input id="ans1" type="radio" name="ans" value="b">{{ exam.Ans2 }}</label></h3>
            <h3><label><input id="ans1" type="radio" name="ans" value="c">{{ exam.Ans3 }}</label></h3>
            <h3><label><input type="radio" name="ans" value="d">{{ exam.Ans4 }}</label></h3>

        {% endif %}
       <p style="color: red"> {{ ans }}</p>

    </div>
    <div class="n">
        <button type="submit" id="cancelTest" class="btn btn-blue"> Answer</button>
        <a href="{% url 'exam:question' %} " id="cancelTest" class="btn btn-blue">Next </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


    </div>
</form>
</body>
</html>

Computer Based Exam (CBE)/templates/exam/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>result</title>
    <style>


        h1 {
            color: #338d93;
        }

        #customers {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 70%;
        }

        #customers td, #customers th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #customers tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        #customers tr:hover {
            background-color: #ddd;
        }

        #customers th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #338d93;
            color: white;
        }

        a {

            margin-left: 30px;
            margin-top: 40px;
            background-color: #338d93;
            padding: 20px;
            padding-left: 30px;
            padding-right: 30px;
            position: absolute;
            horiz-align: center;

        }
    </style>
</head>
<body>
<center><h1>Name : {{ stu_name }}</h1></center>
<br><br>
<center>
    <table id="customers">
        <tr>
            <th>Exam Name :</th>
            <td>{{ course__n }}</td>
        </tr>

        <tr>
            <th>Total Degree :</th>
            <td>{{ total_degree }}</td>
        </tr>
        <tr>
            <th>Degree :</th>
            <td>{{ degree }}</td>
        </tr>
        <tr>
            <th>Question Number :</th>
            <td>{{ count }}</td>
        </tr>
        <tr>
            <th> Answered Question :</th>
            <td>{{ answered }}</td>
        </tr>
        <tr>
            <th>Status :</th>
            <td>{{ passed }}</td>
        </tr>
    </table>
</center>
<div>
    <center>
        <a href="{% url 'student:dashboard' %}" class="btn btn-info" role="button"> <strong>back</strong></a>
    </center>
</div>

</body>
</html>

Computer Based Exam (CBE)/templates/exam/test.html
{% load static %}
<html>

<head>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Computer Based Exam</title>
    <link href="{% static 'resources/style/teplate.css' %}" rel="stylesheet">
    <script src="{% static 'resources/js/jquery-1.js' %}"></script>
    <script src="{% static 'resources/js/bootstrap.js' %}"></script>

</head>

<body class="exampage" oncontextmenu="return false">
<div class="main container-fluid">
    <div class="row-fluid">
        <div class="content span12">
            <div class="main-content">
                <fieldset class="well">
                    <div class="header">

                        <img class="oes-logo" src="{% static 'resources/images/inner-mkcloeslogo.png' %}" alt="">
                        <img class="mkcl-logo" src="{% static 'resources/images/1_companylogo.png' %}" alt="">

                        <div class="eventname-title">{{ ex_name }}</div>
                    </div>

                    <form action="{% url 'exam:result' %}" method="post" id="frmendTest">
                        {% csrf_token %}
                        <div>
                            <div class="span3">
                                <div class="holder">
                                    <div class="profile-timer">
                                        <div class="dp">
                                            <img src="{% static 'resources/images/defaultCandidate.jpg' %}">
                                        </div>
                                        Time Remaining
                                        <span id="time-text"> </span>
                                        <input id="endExamEnablePercentage" name="eQuestion_nondExamEnablePercentage"
                                               value="100"
                                               type="hidden">

                                        <input id="hidTtlDuration" value="1800" type="hidden">
                                        <input id="hidelapsedTimeDuration" value="61" type="hidden">
                                        <input id="timeLeft" value="29:59" type="hidden">
                                        <input id="updateElapsedTime" value="60" type="hidden">
                                        <span></span>
                                    </div>
                                    <div class="totalq">Total number of Questions : <strong
                                            id="ttlcount">{{ count }}</strong>
                                        <div class="legend">
                                            <span class="attempted"><span id="Cntans" class="btn btn-greener">15</span> Answered</span>
                                            <span class="current"><span id="CntNans" class="btn btn-red">0</span> Not Answered</span>
                                            <span class="unattempted"><span id="Cntntvisited" class="btn">0</span> Not Visited</span>
                                        </div>
                                    </div>
                                    <div class="palette">
                                        <div class="quick-ques">
                                            {% for e in exam %}
                                                <a title="Answered" data-status="noans" class="btn btn-greener"
                                                   id="lnk1525"
                                                   href="{% url 'exam:blank' e.Question_no %}"
                                                   target="QuestionContainer">{{ e.Question_no }}</a>
                                            {% endfor %}


                                        </div>
                                        <div class="actions">
                                            <button class="btn btn-red" id="endTest" name="endTest"
                                                    type="submit">End Test
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="span9">
                                <div class="holder">
                                    <br>
                                    <br>


                                    <label class="alert-error" id="error" style="display: none"></label>
                                    <div class="questions-area">
                                        <iframe src="{% url 'exam:question' %}" id="QuestionContainer"
                                                name="QuestionContainer"></iframe>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </fieldset>
            </div>

        </div>
    </div>
</div>
<script>
    var s = 0;
    var m = {{ time }};

    // Update the count down every 1 second
    var x = setInterval(function () {
        if (s == 0) {
            if (m == 0) {
                document.getElementById("time-text").innerHTML = "time expired ";
                document.getElementById("endTest").click();
                delay(function () {
                }, 5000); // end delay

            } else {
                m -= 1;
                s = 60;
            }
        } else {
            s -= 1;
            var minutes = m;
            var seconds = s;
            if (m < 10) {
                minutes = "0" + m;
            }
            if (s < 10) {
                seconds = "0" + s;
            }
            document.getElementById("time-text").innerHTML = minutes + ":" + seconds;

        }
    }, 1000);
</script>
</body>

</html>