Computer Based Exam (CBE)/CBE/urls.py
from django.contrib import admin
from django.urls import path, include
from student.views import home, student_log

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  path('student/', include('student.urls', namespace='student')),
                  path('candidate/', student_log, name='student'),
                  path('adminstrator/', include('adminstrator.urls', namespace='adminstrator')),
                  path('doctor/', include('doctor.urls', namespace='doctor')),
                  path('exam/', include('exam.urls', namespace='exam')),
                  path('detection/', include('detection.urls', namespace='detection')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Computer Based Exam (CBE)/adminstrator/urls.py
from django.conf.urls import url
from . import views

app_name = 'adminstrator'

urlpatterns = [
    url('log/', views.log, name='log'),
    url('admin_page/', views.admin_page, name='admin_page'),
    url('add_doctor/(?P<a_ssn>\d+)/', views.add_doctor, name='add_doctor'),
    url('add_student/(?P<a_ssn>\d+)/', views.add_student, name='add_student'),
    url('reg_doctor/(?P<a_ssn>\d+)/', views.Adddoctor, name='Adddoctor'),
    url('reg_student/(?P<a_ssn>\d+)/', views.Addstudent, name='Addstudent'),

]

# <int:a_ssn>

Computer Based Exam (CBE)/adminstrator/models.py
from django.db import models


class Administrator(models.Model):
    A_ID = models.IntegerField(null=False, unique=True)
    A_ssn = models.BigIntegerField(primary_key=True, unique=True)
    A_name = models.CharField(null=False, max_length=80)

Computer Based Exam (CBE)/adminstrator/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse

from .models import Administrator
from doctor import models as doc
from student import models as stu


def log(request):
    return render(request, 'adminstrator/admin_log.html', {})


def admin_page(request):
    if request.method == 'POST':

        u = request.POST['id']
        p = request.POST['password']
        if u != "" and p != "":
            if Administrator.objects.filter(A_ID=u, A_ssn=p):
                a = Administrator.objects.get(A_ID=u, A_ssn=p)
                context = {'name': a.A_name,
                           'a_ssn': a.A_ssn}

                return render(request, 'adminstrator/admin_page.html', context)
            else:
                messages.error(request, 'ID or password not correct')
                return redirect(reverse("adminstrator:log"))
        else:
            messages.error(request, 'ID or password not correct')
            return redirect(reverse("adminstrator:log"))


def add_doctor(request, a_ssn=None):
    admin = get_object_or_404(Administrator, A_ssn=a_ssn)
    context = {'admin': admin}
    return render(request, 'adminstrator/add_doctor.html', context)


def add_student(request, a_ssn=None):
    admin = get_object_or_404(Administrator, A_ssn=a_ssn)
    context = {'admin': admin}
    return render(request, 'adminstrator/add_student.html', context)


def Adddoctor(request, a_ssn=None):
    admin = get_object_or_404(Administrator, A_ssn=a_ssn)
    context = {'admin': admin}
    doctor = doc.Doctor(D_name=request.POST['D_name'],
                        D_id=request.POST['D_id'],
                        D_ssn=request.POST['D_ssn'],
                        D_faculty=request.POST['D_faculty'],
                        D_department=request.POST['D_department'],
                        D_address=request.POST['D_address'],
                        A_ssn_id=a_ssn)

    doctor.save()
    return render(request, 'adminstrator/add_doctor.html', context)


def Addstudent(request, a_ssn=None):
    admin = get_object_or_404(Administrator, A_ssn=a_ssn)
    context = {'admin': admin}
    student = stu.Student(Stu_name=request.POST['stu_name'],
                          Stu_id=request.POST['stu_id'],
                          Stu_ssn=request.POST['stu_ssn'],
                          Stu_faculty=request.POST['stu_faculty'],
                          Stu_department=request.POST['stu_department'],
                          Stu_level=request.POST['stu_level'],
                          Stu_address=request.POST['stu_address'],
                          A_ssn_id=a_ssn)
    student.save()
    return render(request, 'adminstrator/add_student.html', context)

Computer Based Exam (CBE)/templates/adminstrator/add_doctor.html
{% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'resources/style/teplate.css' %}" rel="stylesheet">
    <script src="{% static 'resources/js/jquery-1.js' %}"></script>
    <script src="{% static 'resources/js/bootstrap.js' %}"></script>
    <title>Add Doctor</title>
    <style type="text/css">
        a {
            cursor: pointer;
        }

        tab_text {
            text-transform: uppercase;
            font-weight: normal;
            font-family: Lucida Sans Unicode Lucida Grande sans-serif;
            text-shadow: 1px 1px 0 #ffffff;
            font-size: 1.071em
        }

        .label-attempt {
            background-color: #fff;
            padding: 1px 2px;
            color: #666;
            border: solid 1px;
            border-color: #666;
            text-shadow: 0 0px 0 rgba(0, 0, 0, 0);
            font-weight: normal;
        }
    
        #answer{
            width: 500px;
            height: 40px;
            font-size: 20px;
        }
        #lnkFreeTakeTest{
            margin-left: 730px;
        }
       
        

    </style>

</head>

<body class="inner" cz-shortcut-listen="true" style="zoom: 1;">
    <div class="main container">
        <div class="row">
            <div class="left-sidebar span3">
                <div id="logo">
                      <img src="{% static 'resources/images/inner-mkcloeslogo.png' %}" alt="OES">
                </div>
                <div class="navbar">
                    <div class="navbar-inner">
                        <div class="container">
                            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                            </a>
                            <div class="nav-collapse collapse">
                                <ul class="nav side-menu">
                                    <li><a href="{% url 'adminstrator:add_doctor' admin.A_ssn %}"><i class="icon-th-large"></i> Add Doctor</a></li>
                                    <li><a href="{% url 'adminstrator:add_student' admin.A_ssn %}"><i class="icon-th-large"></i> Add Student</a></li>
                                </ul>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content span9">
                <div class="content-above">
                    <div class="holder">
                        <div class="profile">
                            <div class="holder">
                                <div class="display-pic">
                                    <div class="dp">
                                        <img src="{% static 'resources/images/defaultCandidate.jpg' %}">
                                    </div>
                                </div>
                                <div class="display-info">
                                    <p>{{admin.A_name}}</p>
                                    <div class="btn-group">
                                        <a href="{% url 'adminstrator:log' %}" class="btn btn-orange">
                                            <font>Logout</font>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-top">
                    <div class="holder">
                    </div>
                </div>
                <div class="main-content">
                    <fieldset class="well">

                        <legend>
                            <span><img src="{% static 'resources/images/dashboard.png' %}" alt=""> Add<span class="pull-right"></span>
                            </span></legend>


                        <div class="holder">
                            <div id="tabbable">
                                <ul class="nav nav-tabs" id="myTab">
                                    <li class="active"><a href="#" data-toggle="tab" class="tab_text" style=" font-weight: bold; font-size:18px; text-shadow: 2px 2px 0 #ffffff;">Add Doctor </a></li>

                                </ul>
                            </div>
                            <div id="showScheduledPapers">


                                <div class="box">
                                    <div class="box-body">
                                     <form  id="add_doctor" action="{% url 'adminstrator:Adddoctor' admin.A_ssn %}" method="POST">
                                    {% csrf_token %}
                                        <table class="table table-bordered table-complex" style="border-top: 0;">
                                            <thead>
                                                <tr>
                                                    <th colspan="3" class="text-left"> </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    
                                                      <td>  
                                                       
                                                         
                                                           <label style="font-size:18px;width: 150px;" class="icon-user">Name</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" class="form-control" name="D_name" id="answer" required pattern="[A-Za-z ]+" title="string only" ><br>
                                                           <label style="font-size:18px;width: 150px;" class="icon-user">ID</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" class="form-control" name="D_id" id="answer" required pattern="[0-9]+" title="number only"><br>
                                                           <label style="font-size:18px;width: 150px;" class="icon-user">National ID</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" class="form-control" name="D_ssn" id="answer" required pattern="[0-9]+" title="number only"><br>
                                                           <label style="font-size:18px;width: 150px;" class="icon-user">Faculty</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" class="form-control" name="D_faculty" id="answer" required pattern="[A-Za-z ]+" title="string only" ><br>
                                                           <label style="font-size:18px;width: 150px;" class="icon-user">department</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" class="form-control" name="D_department" id="answer" required pattern="[A-Za-z ]+" title="string only" ><br>
                                                           <label style="font-size:18px;width: 150px;" class="icon-user">Address</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" class="form-control" name="D_address" id="answer"><br>
                                                         <br>  <button id="lnkFreeTakeTest" data-mode="FullScreen" data-dcidcnt="" class="btn btn-greener lnkFreeTakeTest"  type="submit"  >ADD</button>

                                                   
                                                </tr>

                                            </tbody>

                                        </table>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                 
                </div>
                <br>

                <div class="footer span9">
                    <div class="holder">
                        <p class="pull-left">Copyright © 2018 CBE. All Rights Reserved.</p>
                        <a id="to-top" class="btn btn-grey pull-right" href="#"><i class="icon-chevron-up icon-greyer"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

Computer Based Exam (CBE)/templates/adminstrator/add_student.html
{% load static %}

<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'resources/style/teplate.css' %}" rel="stylesheet">
    <script src="{% static 'resources/js/jquery-1.js' %}"></script>
    <script src="{% static 'resources/js/bootstrap.js' %}"></script>
    <title>Add Student</title>
    <style type="text/css">
        a {
            cursor: pointer;
        }

        tab_text {
            text-transform: uppercase;
            font-weight: normal;
            font-family: Lucida Sans Unicode Lucida Grande sans-serif;
            text-shadow: 1px 1px 0 #ffffff;
            font-size: 1.071em
        }

        .label-attempt {
            background-color: #fff;
            padding: 1px 2px;
            color: #666;
            border: solid 1px;
            border-color: #666;
            text-shadow: 0 0px 0 rgba(0, 0, 0, 0);
            font-weight: normal;
        }
      
        #answer{
            width: 500px;
            height: 40px;
            font-size: 20px;
        }
        #lnkFreeTakeTest{
            margin-left: 730px;
        }
        

    </style>

</head>

<body class="inner" cz-shortcut-listen="true" style="zoom: 1;">
    <div class="main container">
        <div class="row">
            <div class="left-sidebar span3">
                <div id="logo">
                      <img src="{% static 'resources/images/inner-mkcloeslogo.png' %}" alt="OES">
                </div>
                <div class="navbar">
                    <div class="navbar-inner">
                        <div class="container">
                            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                            </a>
                            <div class="nav-collapse collapse">
                                <ul class="nav side-menu">
                                    <li><a href="{% url 'adminstrator:add_doctor' admin.A_ssn %}"><i class="icon-th-large"></i> Add Doctor</a></li>
                                    <li><a href="{% url 'adminstrator:add_student' admin.A_ssn %}"><i class="icon-th-large"></i> Add Student</a></li>
                                </ul>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content span9">
                <div class="content-above">
                    <div class="holder">
                        <div class="profile">
                            <div class="holder">
                                <div class="display-pic">
                                    <div class="dp">
                                        <img src="{% static 'resources/images/defaultCandidate.jpg' %}">
                                    </div>
                                </div>
                                <div class="display-info">
                                    <p>{{admin.A_name}}</p>
                                    <div class="btn-group">
                                        <a href="{% url 'adminstrator:log' %}" class="btn btn-orange">
                                            <font>Logout</font>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-top">
                    <div class="holder">
                    </div>
                </div>
                <div class="main-content">
                    <fieldset class="well">

                        <legend>
                            <span><img src="{% static 'resources/images/dashboard.png' %}" alt=""> Add<span class="pull-right"></span>
                            </span></legend>


                        <div class="holder">
                            <div id="tabbable">
                                <ul class="nav nav-tabs" id="myTab">
                                    <li class="active"><a href="#" data-toggle="tab" class="tab_text" style=" font-weight: bold; font-size:18px; text-shadow: 2px 2px 0 #ffffff;">Add Student </a></li>

                                </ul>
                            </div>
                            <div id="showScheduledPapers">


                                <div class="box">
                                    <div class="box-body">
                                    <form id="add_student" action="{% url 'adminstrator:Addstudent' admin.A_ssn %}" method="POST">
                                    {% csrf_token %}
                                        <table class="table table-bordered table-complex" style="border-top: 0;">
                                            <thead>
                                                <tr>
                                                    <th colspan="3" class="text-left"> </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                    <tr>
                                                    
                                                            <td>  
                                                             
                                                               
                                                                 <label style="font-size:18px;width: 150px;" class="icon-user">Name</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" class="form-control" name="stu_name"id="answer" required pattern="[A-Za-z ]+" title="string only" ><br>
                                                                 <label style="font-size:18px;width: 150px;" class="icon-user">ID</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" class="form-control" name="stu_id" id="answer" required pattern="[0-9]+" title="number only"><br>
                                                                 <label style="font-size:18px;width: 150px;" class="icon-user">National ID</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" class="form-control" name="stu_ssn" id="answer" required pattern="[0-9]+" title="number only"><br>
                                                                 <label style="font-size:18px;width: 150px;" class="icon-user">Faculty</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" class="form-control" name="stu_faculty" id="answer" required pattern="[A-Za-z ]+" title="string only" ><br>
                                                                 <label style="font-size:18px;width: 150px;" class="icon-user">department</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" class="form-control" name="stu_department"id="answer" required pattern="[A-Za-z ]+" title="string only" ><br>
                                                                 <label style="font-size:18px;width: 150px;" class="icon-user">Level Of Study</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" class="form-control" name="stu_level" id="answer" required pattern="[0-9]+" title="number only" ><br>
                                                                 <label style="font-size:18px;width: 150px;" class="icon-user">Address</label>&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" class="form-control" name="stu_address" id="answer"><br>
                                                               <br>  <button id="lnkFreeTakeTest" data-mode="FullScreen" data-dcidcnt="" class="btn btn-greener lnkFreeTakeTest"  type="submit">ADD</button>
                                                          
                                                            
                                                         
                                                      </tr>
      
                                            </tbody>

                                        </table>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                 
                </div>
                <br>

                <div class="footer span9">
                    <div class="holder">
                        <p class="pull-left">Copyright © 2018 CBE. All Rights Reserved.</p>
                        <a id="to-top" class="btn btn-grey pull-right" href="#"><i class="icon-chevron-up icon-greyer"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

Computer Based Exam (CBE)/templates/adminstrator/admin_page.html
{% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'resources/style/teplate.css' %}" rel="stylesheet">
    <script src="{% static 'resources/js /jquery-1.js' %}"></script>
    <script src="{% static 'resources/js/bootstrap.js' %}"></script>
    <title>Admin</title>
    <style type="text/css">
        a {
            cursor: pointer;
        }

        tab_text {
            text-transform: uppercase;
            font-weight: normal;
            font-family: Lucida Sans Unicode Lucida Grande sans-serif;
            text-shadow: 1px 1px 0 #ffffff;
            font-size: 1.071em
        }

        .label-attempt {
            background-color: #fff;
            padding: 1px 2px;
            color: #666;
            border: solid 1px;
            border-color: #666;
            text-shadow: 0 0px 0 rgba(0, 0, 0, 0);
            font-weight: normal;
        }
        .looogo{
            width: 500px;
            margin-left: 200px;
            margin-top: 130px;
        }

    </style>

</head>

<body class="inner" cz-shortcut-listen="true" style="zoom: 1;">
    <div class="main container" >
        <div class="row" >
            <div class="left-sidebar span3" >
                <div id="logo">
                    <img src="{% static 'resources/images/inner-mkcloeslogo.png' %}" alt="OES" >
                </div>
                <div class="navbar">
                    <div class="navbar-inner">
                        <div class="container">
                            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                            </a>
                            <div class="nav-collapse collapse">
                                <ul class="nav side-menu">
                                    <li><a href="{% url 'adminstrator:add_doctor' a_ssn  %} "><i class="icon-th-large"></i> Add Doctor</a></li>
                                    <li><a href="{% url 'adminstrator:add_student' a_ssn %}"><i class="icon-th-large"></i> Add Student</a></li>
                                </ul>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content span9">
                <div class="content-above">
                    <div class="holder">
                        <div class="profile">
                            <div class="holder">
                                <div class="display-pic">
                                    <div class="dp">
                                        <img src="{% static 'resources/images/defaultCandidate.jpg' %}">
                                    </div>
                                </div>
                                <div class="display-info">
                                    <p>{{name }}</p>
                                    <div class="btn-group">
                                        <a href="{% url 'adminstrator:log' %}"class="btn btn-orange">
                                            <font>Logout</font>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-top">
                    <div class="holder">
                    </div>
                </div>
                <fieldset class="well">

                    <legend>
                            <span><img src="{% static 'resources/images/dashboard.png' %}" alt=""> Main<span class="pull-right"></span>
                            </span></legend>



                    <div >

                        <img class="looogo"src="{% static 'resources/images/1_mkcloeslogo.png' %} " alt="" >

                    </div>
                </fieldset>
                 
                </div>
                <br>

                <div class="footer span9">
                    <div class="holder">
                        <p class="pull-left">Copyright © 2018 CBE. All Rights Reserved.</p>
                        <a id="to-top" class="btn btn-grey pull-right" href="#"><i class="icon-chevron-up icon-greyer"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>